feat: [#1] 엔티티 설계 및 결과 페이지
b4-after/K-BNT-15-question-server pull request #1
Opened 2023-04-16 15:53 UTC by leehjhjhj

@ldk980130 
## Postman 결과

![image](https://user-images.githubusercontent.com/102458609/232324399-7f60bec5-f9ed-465c-836e-3b3fccf5c816.png)

## Motivation 🤔
- 동규님 피드백 받고 도메인 주도 설계에 맞춰서 최대한 노력해보았습니다.

## Key changes ⭐️
- 도메인 영역에 침범하지 않도록 짜보았습니다.
- 도메인을 화면에 맞추지 않도록 노력해보았습니다
- 결과페이지의 명세에 맞게 코드를 작성하였습니다.
- 쓸 데 없는 @setter를 제거하였습니다.

## To Reviewers 🙏
- Results 와 ResultsService 저렇게 MakeResults라는 스태틱 클래스를 둬도 되는지 궁금합니다.
- (access = AccessLevel.PROTECTED) 저렇게 붙이는게 맞나요?
- 처음 이렇게 길게 짜보아서 엉터리인 부분이 많을 것 같습니다. 가감없이 지적해주면 감사하겠습니다.

2023-04-17 03:54 UTC, ldk980130 requested changes
안녕하세요 현제님! 피드백 반영해주신거 잘 보았습니다. 처음보다는 훨씬 나아진 것 같아요!  몇 가지 더 개선했으면 좋겠는 점이 보여서 피드백랑 질문 조금 남겼습니다. 

투머치인것 같아 조금 줄였는데도 10개나 리뷰를 남겼네요...ㅋㅋㅋㅋ 질문이나 반박(?) 언제든지 환영하니까 시간날 때 반영해주세요!

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/controller/ResultsController.java
> +    @GetMapping("/results/{memberId}")
사소한거긴 하지만 url만 `results`로 복수형으로 가져가고 코드 내부에서는 `Result`라고 단수로 쓰면 될 것 같아요. `Results`라고 복수라고 쓰면 일급 컬렉션이라고 착각할 수도 있을 것 같네요.

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Answer.java
> +    private String audio;
1. 칼럼명과 필드명을 다르게 가져가신 이유가 있을까요?
2. 만약 데이터베이스 칼럼 이름을 필드명과 다르게 가져가고 싶으면 `JoinColumn`이 아니라 그냥 `Column`을 쓰시면 됩니다.

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Question.java
> +    }
사실 `Question`을 생성하는 기능이 없긴해서 사용되지 않을 생성자같네요. 없애도 되지 않을까요?

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Results.java
> +public class Results {
1. `Result`는 엔티티가 아니기 때문에 기본 생성자가 필요 없을 것 같아요~
2. 이것도 단수로 바꿔주세요. 복수형이면 일급 컬렉션으로 착각할 수도 있을 것 같습니다.

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/dto/AnswerResponseDto.java
> +//}
안쓰는 클래스인가요? 주석으러 처리할거면 지워도 되지 않을까요?

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/repository/AnswerRepositoryImpl.java
> +@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
엔티티에만 붙이면 됩니다. 다른 클래스에는 붙이지 않아도 돼요!

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/AnswerService.java
> +@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
이것도 없애도 됩니다

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        Member member = em.find(Member.class, memberId);
`Answer`가 `Member`를 가지고 있으니까 굳이 `entityManager`를 통해 가져올 필요가 없을 것 같아요!
`Answer.getMember()`

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        return new Results(averageScore, totalScore, resultsList);
Result를 생성하는 로직이 복잡하네요! 
``` java
    public Results findResults(Long memberId) {
        List<Answer> answers = answerRepository.findByMemberId(memberId);
        return new Results(answers);
    }
```

위와 같이 만들어볼 수도 있지 않을까요?

2023-04-17 03:54 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +            if (answer.getAnswerStatus() == AnswerStatus.CORRECT) {
`answer.isCorrect()`와 같이 객체에게 메시지를 보내는 식으로 메서드를 만들면 더 가독성 있을 것 같아요! 그래서 로직을 짤 때 getter를 지양하라는 말도 있어요.

2023-04-17 04:31 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/controller/ResultsController.java
> +    @GetMapping("/results/{memberId}")
넵 url말고 result로 통일하겠습니다~!

2023-04-17 04:32 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Question.java
> +    }
테스트 때문에 넣어놨긴 했는데 없애도 될 것 같아요!

2023-04-17 04:35 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/dto/AnswerResponseDto.java
> +//}
어이쿠 까먹었었네요ㅋㅋ ㅠ 삭제했습니다

2023-04-17 04:36 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/repository/AnswerRepositoryImpl.java
> +@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
넵 알겠습니다!

2023-04-17 04:40 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Answer.java
> +    private String audio;
엇 joinColumn 잘못 복붙한 것 같아요 ㅋㅋ ㅠ 동규님 말대로 audioUrl해도 알아서 audio_url로 되는 것 같아요!

2023-04-17 04:46 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +            if (answer.getAnswerStatus() == AnswerStatus.CORRECT) {
오 정말 좋은 것 같아요! 반영하겠습니다

2023-04-17 05:30 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        return new Results(averageScore, totalScore, resultsList);
어라 그렇게도 가능한가요? 명세대로 만드느라 이렇게 만들었었는데 Result라는 객체를 아예 명세에 맞게 맞춰보았습니다. answers를 그대로 넣으면 담기지가 않아서 ㅠㅠ 좋은 방법이 있나요?

2023-04-17 05:36 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        Member member = em.find(Member.class, memberId);
Answer.getMember()가 가능한가요?? 빼오려면 answers에서 뽑아와야 되는데,, for문에서 answer에서 뽑아오기엔 너무 필요 없는 get이 많을 것 같아서 엔티티 매니저를 사용했습니다!

2023-04-17 05:42 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        return new Results(averageScore, totalScore, resultsList);
아니면 서비스에서가 아니라 Result에 저 getAverage와 calculateScore를 넣으면 어떨까하는 말씀이실까요?

2023-04-17 05:48 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        Member member = em.find(Member.class, memberId);
아니면 `entityManager`를 직접 사용하기 보다 `MemeberRepository`를 만드는 건 어떠신가요?

2023-04-17 05:50 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        return new Results(averageScore, totalScore, resultsList);
넵 그게 맞습니다! 점수를 계산하고, 평균을 계산하는 로직을 `Result`로 옮기면 어떨까였습니다. 이렇게 그대로 해도 상관은 없지만 `getAverage`, `calculateScore` 메서드들은 외부 클래스에서 사용될 일이 없는 메서드이기 때문에 접근자를 `private`으로 변경해주면 좋을 것 같아요!

2023-04-17 06:09 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        Member member = em.find(Member.class, memberId);
어라 그런 방법이 ㅋㅋ 반영하겠습니다!

2023-04-17 06:13 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/ResultsService.java
> +        return new Results(averageScore, totalScore, resultsList);
아하 확인했습니다 ! 객체 생성해서 List에 add하는 것도 좋지 않아보여서 고민하고 리팩토링해보겠습니다.

2023-04-17 13:14 UTC, leehjhjhj commented
@ldk980130 
피드백 바탕으로 수정해서 다시 커밋했습니다!
궁금한점이 몇 가지 있는데
1. 이렇게 되면 Result는 Dto랑 뭐가 다른가요?
2. Result 생성은 저게 최선일까요..?
3. 저번에 지금 상태가 인메모리 데이터베이스가 가능하다고 하셔서 테스트 코드 짜서 해보았는데 잘 되지 않았습니다 ,, 제 임의로 테이블 생성해서 실험 했었는데 성공은 했습니다! 인메모리 상태일 때 동규님은 어떻게 테스트하시나요?

2023-04-17 13:56 UTC, ldk980130 requested changes
현제님 피드백 반영하신거 확인했습니다!! 제가 너무한걸 수도 있겠지만... 더 수정하면 좋을 것 같아서 다시 RC 날려요...ㅎㅎㅎㅎ 그래도 제가 뭐라도 되는건 아니지만 자바 진영에 익숙해지는 연습이라 생각하시면 좋겠네요 저도 최대한 도와드릴게요!

### Result에 대해
`Result`와 Dto의 차이에 대해선 저도 지금에 와선 거의 없다고 생각해요. 애초에 `Result`가 화면에 맞춘 정보를 담는 친구니까요.  그냥 데이터베이스에서부터 쿼리를 통해 Result를 생성하는 식으로 해서 Answer, Question 등 다른 영역에 있는 객체들에 대한 의존도 끊는 방법도 있었겠죠.  `Answer`나 `Question` 등은 저희 서비스 규칙을 잘 이행하고 의미있는 행동을 하는 도메인이라면 `Result`는 화면이 바뀌는 것에 영향 받는 역할을 `Answer`나 `Question` 대신 짊어지고 Dto스러운 역할을 하는 거라고 저는 생각하고 있어요!

### Result 생성에 대해
제가 private 메서드 등에 대해 개선된 코드를 몇 개 리뷰에 남겨봤는데 참고해봐주세요!

### if-else에 대해
나이에 따른 평균 점수를 계산하는 if-else 로직이 복잡하다고 생각해요. 개선해볼만한 참고 블로그를 남겼으니 한 번 고민해보시는 것도 재밌겠네요.

리뷰를 너무 남기는 것 같네요. 혹시 시간적 여유가 없으시면 제가 조금 개선해서 푸시를 날려도 되지만 현제님이 직접 해보시는게 의미 있을 것 같아서 또 피드백 드립니다. 다음에 코드리뷰를 계속 이런식으로 해드려도 될지, 조금 간소화할지에 대해서는 얘기 나눠봐요. 화이팅!

2023-04-17 13:56 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
``` java
public class Answer {
    // ...

    public boolean isGraded() {
        return answerStatus != AnswerStatus.BEFORE;
    }

    public boolean isCorrect() {
        return answerStatus == AnswerStatus.CORRECT;
    }
}
```

``` java
   private char getOX(Answer answer) {
        if (!answer.isGraded()) {
            return '?';
        }
        if (answer.isCorrect()) {
            return 'O';
        }
        return 'X';
    }
```

이런 방식은 어떨까요?? `Answer` 객체에게 행동을 위임하니 `Service` 코드 양이 줄어들 수 있을 것 같아요

2023-04-17 13:56 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
``` java
    private int calculateScore(List<Answer> answers) {
        return (int) answers.stream()
                .filter(Answer::isCorrect)
                .count();
    }
```
Java의 stream 문법을 쓰면 맞은 개수를 간단하게 구현할 수 있습니다!

2023-04-17 13:56 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
나이에 따라 평균 점수를 반환하는 메서드인데요. 만약 나이에 따른 평균 정책이 바뀌거나 더 늘어난다면 계속 if, else 문을 수정해야되겠네요. 가독성도 그렇게 좋아보이지 않아요.

if else 문을 자바의 Enum을 활용하여 개선하는 블로그 글입니다. 한 번 참고해 보시고 적용해 보는 것도 재밌겠네요 ㅎㅎ
https://techblog.woowahan.com/2527/

2023-04-17 13:56 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
``` java
    private List<MakeResult> makeResults(List<Answer> answers) {
        return answers.stream()
                .map(answer -> new MakeResult(
                        answer.getQuestion().getWord(), 
                        getOX(answer))
                )
                .collect(Collectors.toList());
    }
```
Java Stream 공부해보시면 재밌을겁니다 ㅎㅎ

2023-04-17 13:56 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private List<MakeResult> results;
기본 생성자 없어도 되요. JPA를 사용하는 엔티티가 아니니까요. 그리고 재할당될 일이 없는 변수는 모두 final 키워드를 붙여주는 게 좋습니다!
`private final ...`

2023-04-17 13:56 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private static class MakeResult {
클래스 이름인데 동사로 시작하니 어색해요! 보통 메서드 이름이 동사로 시작하니까요.

2023-04-17 13:56 UTC, ldk980130 commented on src/test/java/com/b4after/bntquestion/service/ResultServiceTest.java
> +    }
``` java
    @Autowired
    private EntityManager em;

    @Test
    void getResultTest() throws JsonProcessingException {
        Member member = new Member(58);
        em.persist(member);
        Result result = resultService.findResult(member.getId());
        ObjectMapper objectMapper = new ObjectMapper();
        String resultJson = objectMapper.writeValueAsString(result);
        System.out.println(resultJson);
    }
```
Member가 없어서 발생하는 오류네요~ 

그리고 테스트를 할 때 `println`으로 찍어서 확인하는 건 일일이 눈으로 확인해야하니 힘들 것 같아요. 한 번 다음에 `AssertJ`와 `Junit`을 활용해서 Java 진영에서 테스트를 어떻게 짜는지 공부해보면 좋을 것 같네요.

2023-04-18 00:08 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
엇 자바에도 if not 같은게 있을 줄이야.. 감사합니당 배워가요! 자바가 익숙하지 않아서 마음대로 안되네요 ㅠㅠ ㅋㅋ

2023-04-18 00:11 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
도메인에 저정도 로직은 넣어도 괜찮나요??

2023-04-18 00:13 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
AnswerState가 BEFORE일 때 어떻게 처리할까 고민했었는데 좋은 방법인 것 같아요 👍

2023-04-18 00:17 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
자바 8 문법도 어서 배워야겠어요! 공부해보겠습니다

2023-04-18 00:19 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private List<MakeResult> results;
앗 빼도록 하겠습니다. 어...그러면 result의 모든 변수에 final 붙이면 될까요?

2023-04-18 00:21 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private static class MakeResult {
ResultsList 로 수정하였습니다!

2023-04-18 00:23 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
아하 enum으로 해결하는 방법도 있군요! 블로그 주소까지.. 감사합니다. 읽어보고 수정해볼게요!

2023-04-18 03:23 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
도메인에 로직이 많을수록 전 좋다고 생각해요! 어떤게 채점 전인건지, 정답인건지를 도메인 본인이 알고 있는게 좋고 그걸 `getter`를 통해 `AnswerStatus`를 `Service`단에서 꺼내와서 로직을 짜는건 객체의 캡슐화를 깨는거라고 생각해요

2023-04-18 03:28 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private List<MakeResult> results;
기본적으로 객체는 불변으로 설계하는게 좋아서 JPA 엔티티나 직렬, 역질렬화가 필요한 `DTO`가 아니면 `final`을 기본적으로 붙이는게 좋긴합니다. 

이 외에도 JPA 엔티티, DTO가 아닌 객체는 변수에 `final`을 고려하는 것이 좋습니다. 어쩔 수 없이 재할당의 우려가 있는 것만 빼고 말이죠.

2023-04-18 03:30 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private static class MakeResult {
`word`와 정답 여부를 담는 친구고 그 자체로 컬렉션이 아니기에 `list` 같은 복수형은 어색한 것 같아요. '채점된 결과'니까 `GradedResult`는 어떨까요?

2023-04-18 13:09 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private List<MakeResult> results;
아하~! 그렇군요. 인텔리 제이에서 알아서 final 붙이라고 경고 주더라고요..ㅎ 다 수정했습니다! 친절한 설명 감사합니다!

2023-04-18 13:09 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    private static class MakeResult {
오 좋은 의견입니다! 수정할게용

2023-04-18 13:12 UTC, leehjhjhj commented on src/test/java/com/b4after/bntquestion/service/ResultServiceTest.java
> +    }
음.. result를 테스트라면 question 객체 생성자와 answer 생성할 때도 setter로 AnswerState를 설정해줘야 돼서 생성자 및 setter를 도메인에 넣어야 되는 일이 발생하는데.. 따로 테스트에 도메인을 만드는 식으로 해야될까요?

2023-04-18 13:15 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
```java
@Getter
    @RequiredArgsConstructor
    private enum AgeAverage {
        AGED_GROUP1(12.37, 55, 64),
        AGED_GROUP2(11.17, 65, 74),
        AGED_GROUP3(10.50, 75, 84),
        AGED_GROUP4(6.64, 85, Integer.MAX_VALUE);
        private final double average;
        private final int minAge;
        private final int maxAge;

        public static double getAverage(int age) {
            AgeAverage ageAverage = Arrays.stream(AgeAverage.values())
                    .filter(range -> age >= range.minAge && age <= range.maxAge)
                    .findFirst()
                    .orElseThrow(() -> new IllegalArgumentException("범위 밖입니다."));
            return ageAverage.getAverage();
            }
        }
```
요런 식으로 짜보았는데 옳게 된 방향일까요?!

2023-04-18 13:18 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
1. 아하! 그러면 처음 제가 막 짝던 도메인 안의 로직들(get ox라던가.. getAverage 라던가..) 화면이 도메인을 침범해서 분리하는게 좋았던거고, 도메인에 관련되고 도메인이 알면 좋은 로직들은 도메인에 있어도 좋다는 말씀이신가요?!
2. 앗 넵 이해했습니다!

2023-04-18 13:26 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
네 맞습니다!! 도메인이 자신의 규칙과 관련된 로직은 많이 가지고 있을 수록 좋은 것 같아요. 도메인이 로직을 수행하도록 해서 Service 단의 코드 양을 줄이면 깔끔해지겠죠? 

물론 무조건 도메인 내부다라는건 아니고 로직에 따라 Service 단에 있을 수밖에 없는 로직들도 있긴 해요. (DB를 조회해야 한다던가) 그래도 최대한 비즈니스 규칙은 도메인이 담당하도록 하는 게 정책이나 규칙이 바뀌었을 때 도메인만 수정하고 다른 곳에서의 변경을 줄일 수 있을 거라 생각합니다.

2023-04-18 13:29 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
넵! 블로그 잘 읽어 보셨군요ㅋㅋㅋㅋ 다 좋은데 네이밍만 조금 수정하면 좋을 것 같아요. 이 Enum이 결국은 '평균 점수'를 알아내주는 친구니까 Enum 이름에 Score가 들어가면 어떨까요? (코드 짤 때 네이밍이 가장 어려운 일이죠..)

상수명도 `AGED_GROUP1`, 2, 3, 4라고 이름 짓는 것도 가독성 있게 변경하고 싶지만 저도 다른 이름이 안떠오르네요ㅋㅋㅋㅋ 55 ~ 65 이런 식이라 얘들을 묶을 단어가 안떠오르네요..

2023-04-18 13:35 UTC, ldk980130 commented on src/test/java/com/b4after/bntquestion/service/ResultServiceTest.java
> +    }
맞습니다. 테스트를 하기 위해 갖춰야할 구성들이 있죠. 만약 '댓글'을 테스트하고 싶으면 '회원', '게시글'이 먼저 저장되어있어야 하는 것 처럼요.

이러한 사전 데이터 셋 등을 '테스트 픽스처'라고 하는데요. 애플리케이션이 복잡할 수록 이 픽스처를 구성하는 것이 어려워지고 거대해지더라구요. 이 픽스처를 가독성 있고 간단하게 만드는데는 정답이 없는 것 같고 저도 매번 프로젝트를 할 때마다 고민하는 것 중 하나에요. 해당 서비스의 도메인 성격에 맞춰 사전 데이터를 쉽게 생성해주는 테스트용 클래스를 만들 때도 있고, 테스트를 실행할 때 특정 sql 파일들을 실행시켜 데이터를 미리 넣어두기도 하는 등 방법은 많아요.

현재 서비스는 도메인 복잡도가 크지 않으니 당장은 현제님이 하신 방법대로 테스트 픽스처를 만드는 것도 방법이긴 해요. 그런데 테스트를 하기 위해 코드가 추가되는 것은 지양해야하긴 해요. (테스트를 하기위해 setter를 만든다던가) 테스트 때문에 생성자가 존재하는 건 이번엔 어쩔 수 없으니 허용하는 걸로 해도 괜찮을 것 같긴합니다.

++ isEqualTo() 메서드를 통해 검증하신 것 👍👍 다른 모든 속성들도 이런 방식으로 검증하여 굳이 눈으로 확인할 필요 없이 테스트를 짜면 좋습니다. `println()`하는 코드를 모두 제거하면 좋을 것 같아요~

2023-04-18 13:45 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
그렇군요!! 설명 감사합니다 ☺️ 이제야 조금씩 이해되는 것 같아요!!

2023-04-18 13:47 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +    }
음음 그럼 AgeAverageScore .. 정도가 최선일 것 같아요 ㅠㅠ ㅋㅋㅋ 처음 상수에 AGED_55_64 이런식으로 했는데, 만약 범위가 바뀌면 더 번거로울 것 같아서 1, 2, 3, 4로 붙였습니다 ㅋㅋ ㅠ 이대로 진행할게요!

2023-04-18 13:48 UTC, leehjhjhj commented on src/test/java/com/b4after/bntquestion/service/ResultServiceTest.java
> +    }
헉 궁금했던 걸 이렇게 시원하게 알려주시다니~! 매우 감사합니당.. 요번에는 일단 생성자 넣고 진행하겠습니다!! Assertions 써서 테스트하는 것에 더욱 익숙해져야 겠군요! 텍스트 픽스처라는 거 잘 배워갑니다!

2023-04-18 14:07 UTC, leehjhjhj commented
@ldk980130 
## 변경점
 - Result 내 makeResults 메소드, calculateScore 메소드 람다 스트림으로 리팩토링, 나이에 따른 평균 점수 내는 로직을 enum으로 리팩토링
- Result getOX리팩토링, 이를 위한 Answer내 isGraded, isCorrect 메소드 생성
- Test를 위한 Question 생성자 및 Answer 오버로드 생성자 추가
- Test isEqualTo()로 수정
####
동규님 상세한 리뷰 정말 감사드려요! 많이 배우고 있습니다. 사실 이렇게 상세하게 리뷰 적는 것도 수고가 엄청 들어가는 일인데 자세하게 봐주셔서 정말 감사드려요! 연습도 잘 되고 동규님 설명 이해도 잘 됩니다! 어디 다른 곳 멘토하셔도 될 것 같아요 ㅎㅎ
리뷰 방식에 대해서는 동규님만 괜찮다면 이렇게 해도 정말 좋습니다! 스프링에 재미가 붙이고 있어요 ㅋ.ㅋ

2023-04-19 04:04 UTC, ldk980130 approved these changes
기나긴 코드리뷰 수고 많으셨습니다!  코드리뷰가 도움이 된다니 다행입니다 😄 처음에 비해 코드가 많이 깔끔해진 것 같아요.

`Result` 내부에 있는 `AgeAverageScore` `Enum`만 외부로 빼시면 이젠 approve해도 될 것 같아요. 이 PR이 머지되면 저도 작업 시작해볼게요. 

approve는 하겠지만 더 생각해볼만한 점은 남겨놓을게요.
1. 회원이 없을 때 결과 조회 api를 부르면 500에러가 나는데 에러 처리는 어떻게 할지? (`ControllerAdvice`, `ExceptionHandler`)
2. `memberRepository.findMember()`에서 `member`가 없으면 `null`을 반환하기 때문에 `NullpointerException`이 발생할 수 있어요. `null` 처리를 어떻게 하면 좋을까요? (`Optinal`)

이건 차차 생각해보는 걸로 하고 이만 aprove 하겠습니다. 결과 조회 기능 수고하셨어요!

2023-04-19 04:04 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +        }
`Result` 클래스 내부가 아닌 외부 클래스로 빼면 좋을 것 같아요!

2023-04-19 05:44 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Result.java
> +        }
넵 리팩토링 하였습니다! 동규님도 세세한 리뷰 남겨주시느라 수고많으셨어요 👏
남겨주신 두 가지 예외처리 방법 공부하고 고민해서 또 pr 날려보겠습니다! 머지 진행할게요 ^_^

2023-04-19 05:45 UTC, merged