feat: Memeber 생성(초기화면) 추가
b4-after/K-BNT-15-question-server pull request #3
Opened 2023-04-30 05:38 UTC by leehjhjhj

## Key changes ⭐️
- MemberController와 MemberService 추가

<br>

## To Reviewers 🙏
- 멤버를 저장하고 조회를 해봤을 때, createdAt이 null로 나오는 오류가 있습니다,, 코드 보시고 혹시 잘못된 부분이 있으면 말씀해주시면 감사하겠습니다!
- 메소드나 클래스 이름도 이상하면 지적 부탁드립니다!

2023-04-30 06:04 UTC, ldk980130 requested changes
안녕하세요 현제님! `Member` 생성 API 빠르게 만들어 주셨네요ㅎㅎ 저는 Answer API 조금 걸릴 것 같은데 최대한 빨리 작업해 볼게요...ㅎㅎ

## `MemberRequest` 만들기
`Member`를 생성할 때 필요한 데이터를 클라이언트로 받는데 Dto로 받는 게 더 좋아보입니다. 자세한건 코멘트로 달아놓았어요.

## 인수 테스트 작성하기
제가 `ResultAcceptanceTest`에 만든 테스트처럼 전체 api 흐름을 테스트하는 테스트를 만들면 좋겠어요. 저렇게 만들어 놓으면 일일이 포스트맨으로 테스트할 필요가 없어져서 좋더라구요! 제가 짠거 보면서 + 구글링 하면서 따라 해보시면 포스트맨을 쓸 필요가 없어질겁니다ㅎㅎ

## Jpa Auditing 적용해보기
``` java
public Member(int age) {
        this.age = age;
        this.createdAt = LocalDateTime.now();
    }
```
생성 시간을 만들 때 직접 시간을 찍는 방식을 쓰는데 Jpa Auditing일는 기능을 쓰면 엔티티가 DB에 저장될 때 자동으로 생성 시간을 넣어줍니다. 한 번 공부해보시고 적용하면 좋을 것 같아요!

2023-04-30 06:04 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +    }
엔티티를 그대로 받지 마시고 `MemberRequest`라는 Dto를 생성해서 데이터를 받아주세요. 도메인 엔티티를 `Controller` 계층에 노출하는건 개인적으로 지양하는 편입니다. 도메인에게는 없는 속성을 클라이언트에게 받을 수도 있는 거니까요.

아마 `createdAt`이 `null`인 것은 스프링이 엔티티를 생성하면서 현제님이 만들어놓은 생성자를 쓰지 않기 때문일 겁니다. Dto로 데이터를 받고 `Member`를 현제님의 생성자로 직접 생성하면 생길거에요!

2023-04-30 06:04 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +}
Member를 조회하는 API가 있었나요?

2023-04-30 06:04 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/MemberService.java
> +    }
Service에서 전역적으로 `readOnly=true`를 걸어줬으니 이렇게 데이터를 저장하는 메서드엔 `@Transactional`을 한 번 더 선언해야 데이터가 저장될거에요! H2 환경에서 테스트할 땐 별 문제 없을 수도 있는데 mysql에서 돌리면 무조건 예외 터집니다.

2023-04-30 06:51 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/MemberService.java
> +    }
앗 빠뜨렸었군요,, 수정했습니다!

2023-04-30 06:52 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +}
앗 테스트 때문에 넣어두었습니다. 적어주신 인수테스트 넣고 삭제하겠습니당

2023-05-01 05:10 UTC, ldk980130 requested changes
API 스펙상 맞지 않는 부분이 있어요 이것만 고치면 approve해도 될 듯 합니다!

2023-05-01 05:10 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +    }
API 스펙에 의하면 HTTP 응답 Location 헤더에 `members/{memberId`}를 담아주도록 되어 있어요. 생성된 회원 식별자를 넘겨줘야 `Answer`를 저장할 때 클라이언트에서 사용할 수 있을 테니까요!

2023-05-01 05:10 UTC, ldk980130 commented on src/test/java/com/b4after/bntquestion/acceptance/MemberAcceptanceTest.java
> +        );
`MemberCreateRequest`에 `age`를 넣어주고 요청을 보내야 하지 않을까요? 그리고 201 응답인 것과 함께 Location 헤더에 회원 식별자가 잘 담겨 있는지도 확인하면 좋을 것 같아요! 이 테스트만 봐서는 정말 회원을 저장하고 있는지 불분명하니까요.

response 객체에서 헤더를 어떻게 꺼내는지는 구글링하면 나올겁니다.

2023-05-01 06:06 UTC, leehjhjhj commented on src/test/java/com/b4after/bntquestion/acceptance/MemberAcceptanceTest.java
> +        );
앗 지금 수정중이었습니다 ! ! 자꾸 널떠서 고민 중이었어요,, 수정하고 다시 push하겠습니다!

2023-05-01 06:06 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +    }
넵 확인했습니다!

2023-05-01 06:11 UTC, leehjhjhj commented on src/test/java/com/b4after/bntquestion/acceptance/MemberAcceptanceTest.java
> +        );
@ldk980130 궁금한게 지금 기본생성자로 dto가 되어있어서 나이를 넣으려면 불가피하게 setter를 넣어야되는데 테스트 때문에 setter를 넣으면 혼란이 생기지 않나요??

2023-05-01 06:19 UTC, ldk980130 commented on src/test/java/com/b4after/bntquestion/acceptance/MemberAcceptanceTest.java
> +        );
네 그렇죠 이런 상황엔 2가지 정도 방법이 있을것 같아요

1.dto는 그렇게 안중요(?)하니까 생성자나 setter를 만든다

2. body()에 map을 넣으면 key value를 사용해서 json body를 만들어주니까 map을 쓴다

2023-05-01 06:20 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +    }
++ 추가로 제가 해오던 방식은 헤더에 넣지 않고, 그냥 response body에 회원정보를 넣고 프론트에서 이를 받아서 사용했었는데 헤더에 넣는 이유가 있나요?

2023-05-01 06:32 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +    }
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

201  응답에 생성된 리소스 정보를 바디에 넣어도 되고 location 헤더에 넣어도 되고 둘다 표준 스펙이긴 합니다. 그래서 어떻게 해도 되긴되는데 굳이 dto를 안만들어도 되고 간단히 식별자 하나 리턴하는거라 헤더를 사용하려고 한겁니다!

2023-05-01 06:34 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +    }
아하! 이해했습니다. 헤더에 넣는 거는 처음 해보는 거라 이걸로 진행해보겠습니다!

2023-05-01 06:35 UTC, leehjhjhj commented on src/test/java/com/b4after/bntquestion/acceptance/MemberAcceptanceTest.java
> +        );
오 둘다 해보고 괜찮을 걸로 해보겠습니다 ㅎㅎ 감사합니다!

2023-05-01 13:48 UTC, leehjhjhj commented
## Key changes ⭐️
-  test수정 및 회원 생성시 `location header`에 추가
- `JpaAuditing`를 사용하도록 createdAt 변경(BaseEntity 추가)
- `HttpHeaders`를 이용하여 멤버 생성시 `location header`에 정보 추가
- 테스트에도 header 검사 추가
<br>

## To Reviewers 🙏
- 기존의 `private int age;` 였던 것을 `private Integer age;`로 변경하였습니다. `int`로 하면 전의 코드처럼 비워서 낼 때, 0으로 초기화되어 들어가고, `Integer`로 변경하면 null로 들어간다는 이유에 변경했습니다. 이렇게 처리해도 괜찮을까요?
- `MemberService`에 `HttpHeaders`객체를 반환하도록 만들었습니다. controller에서 `location header`에 memberId를 넣으려면 엔티티가 드러나게 되어서 서비스에 넣었는데 이렇게 서비스에서 `HttpHeaders`를 반환하여 `location header`를 설정하는게 흔한가요?
- 마지막으로 제가 동규님 하신 것 처럼 `JsonPath json = response.jsonPath();`를 통해서 createdAt이나 memberId를 검증하려고 했는데 계속 오류가 뜹니다. 혹시 result처럼 body에 response를 담아 반환하지 않고 .build()로 처리해서 그런걸까요?

2023-05-02 09:05 UTC, ldk980130 requested changes
리뷰 반영 수고하셨습니다! Integer와 서비스에서 HttpHeaders를 반환하는 건에 대해선 코멘트에 답변 달아놓았으니 참고해주세요!

그리고 `MemberAcceptanceTest`에서 `response.jsonPath`를 가져오지 못하는 이유는 애초에 HTTP 응답 바디에 아무것도 없기 때문입니다. 만약 DB에 `Member`가 잘 저장되었는지를 보고 싶다면 `memberRepository`로 따로 검증을 할 필요가 있습니다. 

이번 리뷰 이후에 피드백을 모두 수정하고 나면 이제 approve해도 될 것 같습니다!

2023-05-02 09:05 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +}
```java
@PostMapping("/members/")
    public ResponseEntity<Member> saveMember(@RequestBody MemberCreateRequest memberCreateRequest) {
        Long memberId = memberService.saveMember(memberCreateRequest);
        return ResponseEntity.created(URI.create("/members/" + memberId))
                .build();
    }
```
ResponseEntity의 created()를 이용하면 201 응답코드와 함께 Location 헤더에 값을 넣어줄 수 있습니다!

2023-05-02 09:05 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/domain/Member.java
> +public class Member extends BaseEntity {
`BaseEntity`에 이미 설정해줬기 때문에 `Member`에 `@EntityListener` 어노테이션은 붙이지 않아도 동작할거에요.

2023-05-02 09:05 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/dto/MemberCreateRequest.java
> +}
> 기존의 private int age; 였던 것을 private Integer age;로 변경하였습니다. int로 하면 전의 코드처럼 비워서 낼 때, 0으로 초기화되어 들어가고, Integer로 변경하면 null로 들어간다는 이유에 변경했습니다. 이렇게 처리해도 괜찮을까요?

저도 필드 타입은 웬만하면 래퍼 타입으로 하는 편입니다. 말씀하신 것처럼 0이 들어가면 값을 설정 안해줘서 0인건지, 진짜 0을 사용자가 입력한건지 구분할 수가 없으니까요.

2023-05-02 09:05 UTC, ldk980130 commented on src/main/java/com/b4after/bntquestion/service/MemberService.java
> +    }
서비스 계층에서 웹 계층에 해당하는 `HttpHeaders`를 반환하기 보단 Dto나 Id만 반환하도록 변경하면 좋을 것 같아요!

그리고 이건 로직의 문제인데 저희가 결과페이지에서 보여줄 수 있는 나이 제한이 한정적이잖아요. 그 범위를 벗어나는 나이가 들어왔을 땐 어떻게 처리하는게 좋을까요?

2023-05-02 09:05 UTC, ldk980130 commented on src/test/java/com/b4after/bntquestion/acceptance/MemberAcceptanceTest.java
> +    }
``` java
assertAll(
                () -> assertThat(response.statusCode()).isEqualTo(HttpStatus.CREATED.value()),
                () -> assertThat(response.headers().get("Location").getValue()).isEqualTo("/members/2")
        );
```

단순히 헤더에 값이 있냐고 검증하기보다 더 정확한 값으로 검증하는건 어떨까요? 인수 테스트는 테스트가 실행될 때마다 member 한 명을 기본적으로 insert하기 때문에 이 테스트에서 새로 생성되는 member pk는 2번이라 이렇게 검증해도 통과합니다.

2023-05-02 10:51 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/dto/MemberCreateRequest.java
> +}
이해했습니다! 감사합니다~👍

2023-05-02 10:51 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/domain/Member.java
> +public class Member extends BaseEntity {
앗 넵 확인했습니다! 수정할게요

2023-05-02 10:51 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/controller/MemberController.java
> +}
헉 이렇게 간단했군요.. 좋은 거 배워갑니다!!

2023-05-02 10:55 UTC, leehjhjhj commented on src/test/java/com/b4after/bntquestion/acceptance/MemberAcceptanceTest.java
> +    }
아하 이렇게 검증하면 훨씬 정확하게 되겠군요! 이렇게 수정하도록 하겠습니다 😁

2023-05-02 11:11 UTC, leehjhjhj commented on src/main/java/com/b4after/bntquestion/service/MemberService.java
> +    }
@ldk980130 
저도 `AgeAverageScore` 클래스 만들면서 55세 미만과 85세 이상에 대해서 어떻게 할까 고민이었어요.
```java
public static double getAverageScore(int age) {
        AgeAverageScore ageAverage = Arrays.stream(AgeAverageScore.values())
                .filter(range -> age >= range.minAge && age <= range.maxAge)
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("나이가 평균 점수를 구할 수 있는 범위 밖입니다."));
        return ageAverage.getAverage();
    }
```
이 함수에서 지금은 55세 미만이 되면 예외를 터뜨려 버려서... 차라리 메인에 55세부터 권장한다하고 55세 미만이면 55세~ 64세 그룹의 평균을 보여주는 건 어떨까요? 팀원들과의 상의가 필요할 것 같아요!

2023-05-02 13:48 UTC, leehjhjhj commented
@ldk980130
## Key changes ⭐️
- Location 헤더 추가 로직 변경(ResponseEntity.created으로 변경)
- memberService에서 member의 id만을 반환
- test에 Location 헤더 검증 변경
## To Reviewers 🙏
한번 보시고 더 바꿀 것이 없으면 Approve 해주세요!!

2023-05-02 15:26 UTC, ldk980130 approved these changes
변경 사항 모두 확인하였습니다. 간단한 api였는데 코드 리뷰가 좀 길어졌네요ㅋㅋㅋㅋ 구현 수고하셨습니다!!

2023-05-03 01:45 UTC, merged